import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopLeftImg from "@/components/TopLeftImg";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
// import { useRouter } from "next/router";
import { useRouter } from "next/navigation";
import Transition from "../components/Transition";
import { AnimatePresence, motion } from "framer-motion";
import Layout from "../components/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter;
  return (
    <html lang="en">
      <body className={inter.className}>
      {/* <AnimatePresence mode="wait"> */}
        {/* <motion.div key={router.route} className="h-full"> */}
          {/* <Transition /> */}
        <div className=" page bg-site">
          <TopLeftImg />
          <Nav/>
          <Header />
          {/* <Layout/> */}
          {children}
            </div>
            {/* </motion.div> */}
      {/* </AnimatePresence> */}
      </body>
    </html>
  );
}
